### ISSUE TITLE
nsi.guide is not working

### ISSUE THREAD

**Issue by Maerek** [osmlab/name-suggestion-index#11490]
Hello,

I am reporting a critical issue with the "Name Suggestion Index" website.

Upon attempting to access the page, the screen renders entirely black. After analyzing the source code, I identified a deployment failure: the required JavaScript file is missing. The specific error message is:

`Couldn't find the requested file /dist/javascript/nsiguide.min.js in name-suggestion-index.`

This missing file completely prevents the website from displaying any content, rendering it unusable. Please rectify your deployment immediately by ensuring that `nsiguide.min.js` is correctly placed in the `/dist/javascript/` directory on your CDN.

Thank you.

**Comment by bhousel** [comment]
Thanks for reporting, 
I'm retooling a bunch of stuff, so the static site may be broken for a few days, see #11483, #11488

**Comment by hlfan** [comment]
With the latest release being from mid-August, I doubt the CDN delivers the bun-ready version already.

**Comment by bhousel** [comment]
Yeah, I’m planning to make a new release in the next few days. That’s why I have been changing stuff.

**Comment by riking** [comment]
I am getting a likely-related error:

```
The resource from “https://cdn.jsdelivr.net/npm/name-suggestion-index@latest/dist/javascript/nsiguide.min.js”
  was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
```

Using a pinned version maybe would have allowed the site to continue operating?

**Comment by hlfan** [comment]
The `text/plain` MIME type is just from the file-missing error message.

**Comment by LuisAPI** [comment]
- Request URL: https://cdn.jsdelivr.net/npm/name-suggestion-index@latest/dist/javascript/nsiguide.min.js
- Request Method: GET
- Status Code: 404 Not Found

Chromium's dev tools sidebar says the main JS file the homepage is looking for is missing. The parent folder https://cdn.jsdelivr.net/npm/name-suggestion-index@latest/dist/javascript/ only lists these scripts:

- [nsi.cjs](https://cdn.jsdelivr.net/npm/name-suggestion-index@6.0.20250817/dist/javascript/nsi.cjs)	57.7 KB
- [nsi.cjs.map](https://cdn.jsdelivr.net/npm/name-suggestion-index@6.0.20250817/dist/javascript/nsi.cjs.map)	102.35 KB
- [nsi.iife.js](https://cdn.jsdelivr.net/npm/name-suggestion-index@6.0.20250817/dist/javascript/nsi.iife.js)	61.12 KB
- [nsi.iife.js.map](https://cdn.jsdelivr.net/npm/name-suggestion-index@6.0.20250817/dist/javascript/nsi.iife.js.map)	102.27 KB

**Comment by bhousel** [comment]
It should be working now

**Comment by UKChris-osm** [comment]
A couple of years ago I created the [wikidata-warnings.htm](https://nsi.guide/wikidata-warnings.htm) page to highlight all the Wikidata errors generated when `npm run wikidata` was run, and later @Snowysauce added more detail to the page. However, it seems to have stopped working since all the changes to the NSI - are you able to take a look at some point @bhousel? Perhaps it's just a case of updating the location of the `warnings.json` file, if that still exists?

I've also noticed that the Overpass Turbo link for each entry disappears whenever we have * selected, which was added as part of #11120 @k-yle 

With "*" - without Overpass Turbo links:

<img width="702" height="873" alt="Image" src="https://github.com/user-attachments/assets/10dd6381-c5e4-4e9a-943e-a7af93dea63d" />

With "brands" - with Overpass Turbo links:

<img width="699" height="955" alt="Image" src="https://github.com/user-attachments/assets/6134d841-13b5-497f-915f-1c3c100aec43" />

**Comment by bhousel** [comment]
> A couple of years ago I created the [wikidata-warnings.htm](https://nsi.guide/wikidata-warnings.htm) page to highlight all the Wikidata errors generated when `npm run wikidata` was run, and later [@Snowysauce](https://github.com/Snowysauce) added more detail to the page. However, it seems to have stopped working since all the changes to the NSI - are you able to take a look at some point [@bhousel](https://github.com/bhousel)? Perhaps it's just a case of updating the location of the `warnings.json` file, if that still exists?

Oh yeah , sorry I missed this URL - I just fixed it in 88072e18f
https://nsi.guide/wikidata-warnings.htm looks like it is working again

**Comment by karabineq** [comment]
Since this thread is reopened, I can report that I have suggested adding a new brand - that was added on September 6th - but it is still not visible in iD editor. Here's link to the solved thread:
https://github.com/osmlab/name-suggestion-index/issues/11109#event-19537200734

**Comment by hlfan** [comment]
@karabineq could you try it in [the development version](https://ideditor.netlify.app/)?
The last NSIv6 update was in August, and NSIv7 just missed the iDv2.37 release.
I only bumped that today in openstreetmap/iD#11541.

**Comment by karabineq** [comment]
> [@karabineq](https://github.com/karabineq) could you try it in [the development version](https://ideditor.netlify.app/)? The last NSIv6 update was in August, and NSIv7 just missed the iDv2.37 release. I only bumped that today in [openstreetmap/iD#11541](https://github.com/openstreetmap/iD/pull/11541).

Oh okay, thanks for the help, and yeah it is working there.

**Comment by LuisAPI** [comment]
nsi.guide is stuck at a "Loading, please wait..." message, with the console full of errors:

```
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
    useTaginfo AppContext.jsx:202
    AsyncFunctionThrow self-hosted:804
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
    useFetch AppContext.jsx:140
    AsyncFunctionThrow self-hosted:804
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
    useFetch AppContext.jsx:140
    AsyncFunctionThrow self-hosted:804
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
    useNsi AppContext.jsx:171
    AsyncFunctionThrow self-hosted:804
SES Removing unpermitted intrinsics lockdown-install.js:1:203117
  Removing intrinsics.%MapPrototype%.getOrInsert lockdown-install.js:1:202962
  Removing intrinsics.%MapPrototype%.getOrInsertComputed lockdown-install.js:1:202962
  Removing intrinsics.%WeakMapPrototype%.getOrInsert lockdown-install.js:1:202962
  Removing intrinsics.%WeakMapPrototype%.getOrInsertComputed lockdown-install.js:1:202962
  Removing intrinsics.%DatePrototype%.toTemporalInstant lockdown-install.js:1:202962
Loading failed for the <script> with source “https://browser-update.org/update.js”. nsi.guide:13:52
Download the React DevTools for a better development experience: https://react.dev/link/react-devtools nsiguide.min.js:7:381170
⚠️ React Router Future Flag Warning: React Router will begin wrapping state updates in `React.startTransition` in v7. You can use the `v7_startTransition` future flag to opt-in early. For more information, see https://reactrouter.com/v6/upgrading/future#v7_starttransition. nsiguide.min.js:7:419671
⚠️ React Router Future Flag Warning: Relative route resolution within Splat routes is changing in v7. You can use the `v7_relativeSplatPath` future flag to opt-in early. For more information, see https://reactrouter.com/v6/upgrading/future#v7_relativesplatpath. nsiguide.min.js:7:419671
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdn.jsdelivr.net/npm/@openstreetmap/id-tagging-schema@latest/dist/taginfo.min.json. (Reason: CORS request did not succeed). Status code: (null).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://cdn.jsdelivr.net/npm/name-suggestion-index@latest/dist/json/nsi.min.json. (Reason: CORS request did not succeed). Status code: (null).
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.

```

**Comment by UKChris-osm** [comment]
> nsi.guide is stuck at a "Loading, please wait..." message, with the console full of errors:

Is that happening on a particular page? I can't see any loading issues with the web site at the moment.

**Comment by bhousel** [comment]
> nsi.guide is stuck at a "Loading, please wait..." message, with the console full of errors:

It looks like your browser has some plugin that is blocking the code from running properly?
nsi.guide is working normally for me from a few different devices and browsers I've tested with.

**Comment by bhousel** [comment]
I'm going to close this, since it seems working now, but I opened #11536 so we don't lose track of the Overpass issue.
