### ISSUE TITLE
PostAuto is an operator, not a network.

### ISSUE THREAD

**Issue by dafadllyn** [osmlab/name-suggestion-index#5293]
https://github.com/osmlab/name-suggestion-index/blob/4a15e7536807126543716a7a42f461784b3be672/data/transit/route/bus.json#L9355-L9371

PostAuto [^1] (Wikidata Q666809) is an operator, not a network.

(The networks in Switzerland can be found [here](https://www.sbb.ch/en/travelcards-and-tickets/buying-options/fare-networks.html). As a national bus operator, PostAuto's routes often cross multiple networks. Therefore, `network=*` is usually omitted for PostAuto.)

[^1]: German name: PostAuto; French name: CarPostal; Italian name: AutoPostale; Romansh name: AutoDaPosta

**Comment by kjonosm** [comment]
Hey @dafadllyn! I see your point. But there are currently still some routes tagged with `network=Postauto` in OSM, see e.g. [overpass link](https://overpass-turbo.eu/s/1aNJ). There are also some `network=CarPostal` or `network=Autopostale` around. Maybe these could be fixed first.

**Comment by dafadllyn** [comment]
@kjonosm: Most of these errors (`network=*` instead of `operator=*`) have only been added in the last weeks – possibly because of NSI (Osmose). I've corrected them now.

**Comment by kjonosm** [comment]
> Most of these errors (network=* instead of operator=*) have only been added in the last weeks – possibly because of NSI (Osmose).

This is not entirely correct. For this [route](https://www.openstreetmap.org/relation/2846565/history) `network=Car Postal Suisse` has been tagged since version 1 (8 years ago). NSI only suggests updating the `network` tag if Postauto or a synonym of Postauto are already in use.

**Comment by kjonosm** [comment]
> I've corrected them now.

Hey @dafadllyn. FYI, there are still 14 bus routes with `network=CarPostal` in OSM. So they still show up in NSI...

**Comment by dafadllyn** [comment]
> Hey @dafadllyn. FYI, there are still 14 bus routes with `network=CarPostal` in OSM. So they still show up in NSI...

There were two `network=Car Postal` routes as well as 61 `network:fr=CarPostal` (+ `network=PostAuto` etc.), which have been added in the last few days and which i've all corrected, but i can't find a single `network=CarPostal`. 🤔

**Comment by dafadllyn** [comment]
Searching for `~"network.*"~".*[Cc]ar *[Pp]ostal.*"` with Overpass Turbo doesn't give any result anymore at the moment.

**Comment by kjonosm** [comment]
Thanks for double checking @dafadllyn

I had a look at https://www.openstreetmap.org/relation/4297209 and was indeed surprised to see that even without a `network=*` tag present, iD suggests to update the relation according to the given `operator=*` tag.

@bhousel is this intended by the validation?

**Comment by bhousel** [comment]
> I had a look at https://www.openstreetmap.org/relation/4297209 and was indeed surprised to see that even without a `network=*` tag present, iD suggests to update the relation according to the given `operator=*` tag.
> @bhousel is this intended by the validation?

yes, this was intended, to upgrade routes where people added the `operator` but not the `network`.  But if it's causing more harm than good, I can change what tags the matcher looks at.

The code that does it is here:
https://github.com/openstreetmap/iD/blob/73e5cf01426644ded2b75aa0fc33ac643e1dd7e5/modules/services/nsi.js#L278-L282

**Comment by kjonosm** [comment]
Thanks for the explanation. I think we can leave it as is for now. If we explicitly want to rule out one network we can always list it in the "named" section I guess...
