### ISSUE TITLE
dodgy tag suggestions

### ISSUE THREAD

**Issue by k-yle** [osmlab/name-suggestion-index#6535]
I've been getting some dodgy suggestions recently... 

two of these issues could be fixed by keeping `post_office`/`post_depot` and `fuel`/`car_wash` in sync, but the other two examples are just  incorrect.

<table>
<tr>
	<td><img src="https://user-images.githubusercontent.com/16009897/166179513-a2ad9fee-6dce-4a01-92bc-68490c973320.png" />
	<td><img src="https://user-images.githubusercontent.com/16009897/166179516-8054f691-4053-4b8e-a074-e144e4d54ae2.png"/>
<tr>
	<td><img src="https://user-images.githubusercontent.com/16009897/166179520-28471f7c-ccb0-4bad-9443-9653b57a3f24.png"/>
	<td><img src="https://user-images.githubusercontent.com/16009897/166179521-87a169fa-489a-45d2-b85e-8f600befe4ff.png"/>
</table>

**Comment by arch0345** [comment]
Related to #6517 and #6523

**Comment by k-yle** [comment]
here's another: 
<img src="https://user-images.githubusercontent.com/16009897/166190426-6fa8f739-d2eb-4171-99c5-5bcaf6ae7fa0.png" />

**Comment by UKChris-osm** [comment]
I had one yesterday that tried to suggest a shoe shop be changed into an estate agents, and I think this might be a bit too aggressive, as the store was already marked as a shoe shop, as opposed to an estate agents, or even just a building.

![nsi-taylors](https://user-images.githubusercontent.com/59393694/166295619-8f52ff54-2f25-408d-8a56-ea4f4a6e8c70.png)

**Comment by 1ec5** [comment]
Not sure if it’s a reliable indicator, but the [`not:brand:wikidata`](http://taghistory.raifer.tech/#***/not:brand:wikidata/) usage rate increased noticeably starting on April 11, which corresponds to [this tag](https://github.com/osmlab/name-suggestion-index/releases/tag/v6.0.20220411).

**Comment by arch0345** [comment]
> Not sure if it’s a reliable indicator, but the [`not:brand:wikidata`](http://taghistory.raifer.tech/#***/not:brand:wikidata/) usage rate increased markedly starting on April 11, which corresponds to [this tag](https://github.com/osmlab/name-suggestion-index/releases/tag/v6.0.20220411) ([compare to the April 4 tag](https://github.com/osmlab/name-suggestion-index/compare/v6.0.20220404...v6.0.20220411)).

Maybe this could be caused by dependency updates from these commits? All of the other changes seem to be normal.

- https://github.com/osmlab/name-suggestion-index/commit/4cdd145041147de63c1b6acc613d53fca59212f8
- https://github.com/osmlab/name-suggestion-index/commit/7518fd6d915f30f4344a4f6b48be72285130cc67
- https://github.com/osmlab/name-suggestion-index/commit/d668a4f0cea5985c65ec23d02b2aa3931d6bb623

**Comment by bhousel** [comment]
I'm looking into these now 
@k-yle & @UKChris-osm , the screenshots are great, but can you update the reports to include the osm ids of the features?  Thanks!

**Comment by bhousel** [comment]
Ok, I think what triggered this bug is the introduction of the `operators/building/warehouse.json` file on Apr 3: https://github.com/osmlab/name-suggestion-index/commit/b38623ebaab06cc77ebf70163d9ef915d267b9cd
which would have entered the released NSI data files around [v6.0.20220411](https://github.com/osmlab/name-suggestion-index/releases/tag/v6.0.20220411)

This code in iD/RapiD is the cause of this issue:
https://github.com/facebookincubator/RapiD/blob/02d266bd7a6d4cf732b2e55d7b7e69ef3159d636/modules/services/nsi.js#L180-L187

By adding a category for `building=warehouse` that is kind of like saying that "buildings can be POIs"  (in the same way that shops or amenities are)..  

So previously - NSI would only match certain boring buildings under special conditions (if the feature in iD matched a building preset like `building=yes` and had no other interesting tags)
Now - this code has started considering the `building=` tag "interesting" in a way that it didn't before. 

So _for today_, I'm just going to remove the building/warehouse file (sorry @k-yle)  and I'll think about ways that we can evolve NSI in in a way that it doesn't produce surprises like this.

**Comment by bhousel** [comment]
I just published v6.0.20220503 and it looks fixed 👍 
I'm not offered the tag suggestion from https://github.com/osmlab/name-suggestion-index/issues/6523 anymore about the Sydney Water station w689271366.

Let me know if the tag suggestions are looking better now..

**Comment by k-yle** [comment]
sorry about those warehouses 👀 @bhousel I've added links to each screenshot. it might be a caching thing, but they're all still an issue for me

**Comment by michaelblyons** [comment]
> two of these issues could be fixed by keeping `post_office`/`post_depot` and `fuel`/`car_wash` in sync,

Apologies if off-topic. I just wanted to say that if the list synchronization happens, make sure there is allowance for (eg) `car_wash` locations that are not fuel stations.

**Comment by bhousel** [comment]
> > two of these issues could be fixed by keeping `post_office`/`post_depot` and `fuel`/`car_wash` in sync,
> 
> Apologies if off-topic. I just wanted to say that if the list synchronization happens, make sure there is allowance for (eg) `car_wash` locations that are not fuel stations.

yes, i've thought about making a template rule to just expand all `amenity/fuel` items into `amenity/car_wash` items (or `shop/convenience`)  but I worry that the majority of the time it would be producing a lot of extra items that aren't really useful.
